const item = (id, name, traditional, pinyin, hanzi, short, detail) => Object.freeze({ id, name, traditional, pinyin, hanzi, short, ...(detail ? { detail } : {}) });

export const glossary = Object.freeze({
  bazi: item("bazi", "BaZi", "BaZi · 八字", "Ba Zi", "八字", "Lecture traditionnelle des huit signes formés par les Quatre Piliers.", "Chaque pilier contient un Tronc céleste et une Branche terrestre. Ensemble, ils décrivent une structure symbolique liée à la date et à l’heure locales de naissance."),
  fourPillars: item("fourPillars", "Quatre Piliers", "Si Zhu · 四柱", "Si Zhu", "四柱", "Les piliers de l’Année, du Mois, du Jour et de l’Heure.", "Ils forment les huit caractères du BaZi : quatre Troncs célestes et quatre Branches terrestres lorsque l’heure est connue."),
  dayMaster: item("dayMaster", "Maître du Jour", "Ri Zhu Tian Gan · 日主", "Ri Zhu", "日主", "Le Tronc céleste du Pilier du Jour, point central de la lecture BaZi.", "Les relations du thème sont traditionnellement lues depuis cet élément et sa polarité. Il ne résume pas une personne à lui seul."),
  heavenlyStem: item("heavenlyStem", "Tronc céleste", "Tian Gan · 天干", "Tian Gan", "天干", "Une des dix qualités visibles combinant un élément et une polarité.", "Les dix Troncs parcourent les Cinq Éléments sous leurs formes Yin et Yang."),
  earthlyBranch: item("earthlyBranch", "Branche terrestre", "Di Zhi · 地支", "Di Zhi", "地支", "Une des douze qualités cycliques associées aux animaux du zodiaque.", "Chaque Branche possède un élément principal, une polarité et des Troncs cachés selon la tradition."),
  fiveElements: item("fiveElements", "Cinq Éléments", "Wu Xing · 五行", "Wu Xing", "五行", "Bois, Feu, Terre, Métal et Eau.", "Ce sont des mouvements symboliques reliés par des cycles de génération et de contrôle, et non des substances au sens matériel."),
  yinYang: item("yinYang", "Yin / Yang", "Yin Yang · 陰陽", "Yin Yang", "陰陽", "Deux polarités complémentaires utilisées pour décrire les transformations.", "Yin et Yang ne sont ni bons ni mauvais : ils désignent des tendances relatives qui se répondent."),
  tenGods: item("tenGods", "Dix Dieux", "Shi Shen · 十神", "Shi Shen", "十神", "Dix relations entre le Maître du Jour et les autres Troncs.", "Les appellations varient selon les écoles. TAO emploie une convention française stable et conserve pinyin, Hanzi et variantes dans le glossaire."),
  hiddenStems: item("hiddenStems", "Troncs cachés", "Cang Gan · 藏干", "Cang Gan", "藏干", "Troncs traditionnellement contenus à l’intérieur des Branches terrestres.", "Ils permettent une lecture plus fine des qualités internes d’une Branche."),
  jieQi: item("jieQi", "Termes solaires", "Jie Qi · 節氣", "Jie Qi", "節氣", "Vingt-quatre repères saisonniers fondés sur le mouvement annuel apparent du Soleil.", "Ils divisent l’année solaire en vingt-quatre segments et servent notamment à situer les mois BaZi."),
  naYin: item("naYin", "Na Yin", "Na Yin · 納音", "Na Yin", "納音", "Système traditionnel associant les soixante couples du cycle à trente images élémentaires.", "TAO conserve les appellations traditionnelles pour éviter une traduction réductrice et les accompagne d’une explication française lorsqu’elles sont disponibles."),
  shenSha: item("shenSha", "Étoiles symboliques", "Shen Sha · 神煞", "Shen Sha", "神煞", "Repères symboliques complémentaires dont les règles varient selon les écoles.", "Ils sont présentés comme des indications traditionnelles, jamais comme des certitudes ni des prédictions."),
  daYun: item("daYun", "Grandes périodes", "Da Yun · 大運", "Da Yun", "大運", "Périodes successives de dix années civiles après un démarrage personnel calculé à partir d’un Jie.", "TAO les calcule localement depuis le Pilier du Mois, la polarité annuelle, la convention choisie et l’intervalle naissance–Jie."),
  yongShen: item("yongShen", "Énergie utile", "Yong Shen · 用神", "Yong Shen", "用神", "Concept avancé désignant une fonction d’équilibrage dans certaines méthodes BaZi.", "Il ne doit pas être confondu avec tout élément simplement favorable ou de soutien. TAO ne l’affiche que si le moteur calcule réellement ce concept."),
  generationCycle: item("generationCycle", "Cycle de génération", "Sheng · 生", "Sheng", "生", "Le Bois nourrit le Feu, puis la Terre, le Métal, l’Eau et de nouveau le Bois."),
  controlCycle: item("controlCycle", "Cycle de contrôle", "Ke · 克", "Ke", "克", "Le Bois régule la Terre, la Terre l’Eau, l’Eau le Feu, le Feu le Métal et le Métal le Bois."),
  yijing: item("yijing", "Yi Jing", "Yi Jing · 易經", "Yi Jing", "易經", "Le Livre des transformations, tradition fondée sur les hexagrammes."),
});
